// Copyright 2021 Tencent Inc. All rights reserved.
//
// 境内普通商户退款API
//
// 境内普通商户退款功能涉及的API文档
//
// API version: 1.2.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.github.ji.jpay.dto;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class RefundDTO {

    @ApiModelProperty(value = "门店id")
    private Integer merchantId;

    @ApiModelProperty("商户订单号 说明：原支付交易对应的商户订单号")
    private String outTradeNo;

    @ApiModelProperty("商户退款单号 说明：商户系统内部的退款单号，商户系统内部唯一，只能是数字、大小写字母_-|*@ ，同一退款单号多次请求只退一笔。")
    private String outRefundNo;

    @ApiModelProperty("notify_url")
    private String notifyUrl;

    @ApiModelProperty(value = "支付金额，单位为分")
    private Integer amount;

    @ApiModelProperty("退款金额 ，单位为分")
    private Integer refundAmount;

}
